# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-18 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jus', '0003_auto_20170710_0610'),
    ]

    operations = [
        migrations.AddField(
            model_name='ju',
            name='stop_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
