# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-19 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jus', '0009_auto_20170719_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='ju',
            name='ju_type',
            field=models.CharField(choices=[('order', '凑单'), ('didi', '拼车'), ('plan', '预算')], default='', max_length=30),
        ),
    ]
