# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-22 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jus', '0010_ju_ju_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
