# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-27 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jus', '0013_auto_20170722_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ju',
            name='status',
            field=models.CharField(choices=[('testing', '测试'), ('active', '开始'), ('ordering', '待发货'), ('delivering', '发货中'), ('paying', '收款中'), ('close', '关闭')], default='', max_length=30),
        ),
    ]
