# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-28 04:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jus', '0015_auto_20170728_0851'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationDepart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart_name', models.CharField(default='', max_length=300)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jus.Location')),
            ],
        ),
    ]
