# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-01 10:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jus', '0016_locationdepart'),
    ]

    operations = [
        migrations.AddField(
            model_name='ju',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_jus', to='jus.Ju'),
        ),
    ]
