# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-08 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jus', '0018_locationuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ju',
            name='ju_type',
            field=models.CharField(choices=[('category', '产品目录'), ('order', '凑单'), ('didi', '拼车'), ('plan', '预算'), ('vote', '投票')], default='', max_length=30),
        ),
    ]
