# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-03 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='depart_name',
            field=models.TextField(default='N/A'),
        ),
    ]
