# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-06 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_depart_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
