# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-03 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='display_name',
            field=models.TextField(default=''),
        ),
    ]
