# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-08 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170803_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='group_name',
            field=models.TextField(default=''),
        ),
    ]
