# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-05 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0010_auto_20170703_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='item',
            name='qty',
            field=models.FloatField(default=0.0),
        ),
    ]
