# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-09 00:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0011_auto_20170706_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ju',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lists_ju_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
