# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-09 01:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0012_auto_20170709_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='ju',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jus.Ju'),
        ),
    ]
