# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-16 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0014_auto_20170710_0431'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='qty',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
