# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-15 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0018_auto_20170722_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='text',
            field=models.CharField(default='', max_length=140),
        ),
    ]
