# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-25 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0019_list_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='text',
            field=models.CharField(blank=True, default='', max_length=140, null=True),
        ),
    ]
