# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-27 16:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wechat', '0002_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationHis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msgid', models.TextField(default='')),
                ('label', models.TextField(default='')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('precision', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
